pipeline {
    agent any
    environment {
        AWS_REGION = 'ap-southeast-2'
        ECR_REPO = 'demoecs'
        IMAGE_TAG = "${BUILD_NUMBER}"
        GIT_REPO = 'https://github.com/ronzhang0828/demoECS_Deployment.git'
        GIT_BRANCH = 'deploy'
    }

    stages {
        stage()
    }
}